module Lifetime where
-- 
-- import Syntax
-- import Control.Monad.Reader
-- -- instance Ord Lifetime
-- 
-- lifetimeTerm :: Term -> Typing Lifetime
-- lifetimeTerm term = case term of
--     (Lit n) -> return LiStatic
--     (Var x) -> ask >>= lifet . liLookup x
--     (Lam name (li, ty) t1) ->
